version: "3.2"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    platform: linux/amd64
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "aAbB8764138*"
      ACCEPT_EULA: "Y"
      MSSQL_AGENT_ENABLED: "true"